# .gitpod.yml
tasks:
  - name: Setup Python 3.11
    init: |
      sudo apt-get update
      sudo apt-get install -y python3.11 python3.11-venv
      sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.11 1
      sudo update-alternatives --set python3 /usr/bin/python3.11
      python3 --version

  - name: Create Virtual Environment
    init: |
      python3.11 -m venv ~/.venv-metagpt
      echo 'source ~/.venv-metagpt/bin/activate' >> ~/.bashrc
      source ~/.venv-metagpt/bin/activate

  - name: Install System Dependencies
    init: |
      sudo apt-get install -y build-essential libssl-dev libffi-dev
      curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
      sudo apt-get install -y nodejs npm
      sudo npm install -g pnpm

  - name: Install MetaGPT
    init: |
      set -ex
      source ~/.venv-metagpt/bin/activate
      python3.11 -m pip install --upgrade pip setuptools wheel
      python3.11 -m pip install numpy==1.26.0
      python3.11 -m pip install metagpt==0.8.2 --no-cache-dir
      gp sync-done deps_installed

  - name: Final Configuration
    command: |
      gp sync-await deps_installed
      source ~/.venv-metagpt/bin/activate
      echo -e "\n\033[32m✅ Instalação concluída! Use:\033[0m"
      echo "metagpt 'sua pergunta'"
      echo -e "\n\033[33m🔑 Configure as chaves API:\033[0m"
      echo "https://gitpod.io/user/variables\n"
      metagpt --version

# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
ports:
  - name: Frontend
    description: Port 3000 for the frontend
    port: 3000
    onOpen: open-preview

# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart
