# .gitpod.yml
image:
  file: .gitpod.Dockerfile

ports:
  - port: 3000
    onOpen: ignore

tasks:
  - name: Inicialização do MetaGPT
    init: |
      docker build -t metagpt .
    command: |
      echo -e "\n\033[32m✅ Ambiente Docker pronto!\033[0m"
      echo "Use: docker run -it --rm metagpt metagpt 'sua pergunta'"
      echo -e "\n\033[33m🔑 Configure as variáveis de ambiente no arquivo .env:\033[0m"
      echo "OPENAI_API_KEY=suachaveaqui"