# .gitpod.yml
tasks:
  - name: Docker Setup
    init: |
      # Criar estrutura de diretórios
      mkdir -p /workspace/metagpt/{config,workspace}
      
      # Baixar imagem Docker oficial
      docker pull metagpt/metagpt:latest
      
      # Criar arquivo de configuração padrão se não existir
      if [ ! -f /workspace/metagpt/config/config2.yaml ]; then
        docker run --rm metagpt/metagpt:latest cat /app/metagpt/config/config2.yaml > /workspace/metagpt/config/config2.yaml
        sed -i "s/api_key:.*/api_key: \"${OPENAI_API_KEY}\"/" /workspace/metagpt/config/config2.yaml
      fi
      
      # Sinalizar conclusão
      gp sync-done docker_ready

  - name: MetaGPT Runner
    command: |
      # Esperar Docker estar pronto
      gp sync-await docker_ready
      
      # Mensagem de boas-vindas
      echo -e "\n\033[32m✅ MetaGPT Docker está pronto!\033[0m"
      echo -e "Variáveis de ambiente detectadas:"
      echo -e "OPENAI_API_KEY: ${OPENAI_API_KEY:+*****}"
      echo -e "\n\033[1mComo usar:\033[0m"
      echo -e "1. Execute diretamente:"
      echo -e "   \033[36mmetagpt 'sua pergunta'\033[0m"
      echo -e "2. Acesse o container:"
      echo -e "   \033[36mdocker-shell\033[0m"
      
      # Criar alias para comandos rápidos
      echo -e "\nalias metagpt='docker run -it --rm --privileged -v /workspace/metagpt/config/config2.yaml:/app/metagpt/config/config2.yaml -v /workspace/metagpt/workspace:/app/metagpt/workspace metagpt/metagpt:latest metagpt'" >> ~/.bashrc
      echo -e "alias docker-shell='docker run -it --rm --privileged -v /workspace/metagpt/config/config2.yaml:/app/metagpt/config/config2.yaml -v /workspace/metagpt/workspace:/app/metagpt/workspace --entrypoint /bin/bash metagpt/metagpt:latest'" >> ~/.bashrc
      
      # Recarregar bashrc
      source ~/.bashrc

ports:
  - port: 3000
    onOpen: open-preview
    visibility: public