# .gitpod.yml
tasks:
  - name: Docker Setup
    init: |
      # Criar estrutura de diretórios dentro do repositório
      mkdir -p .metagpt/workspace
      
      # Baixar imagem Docker oficial
      docker pull metagpt/metagpt:latest
      
      # Configurar arquivo com modelo Qwen
      cat << EOF > .metagpt/config2.yaml
      llm:
        api_type: "openai"
        api_key: "${HUGGINGFACE_QWQ32B}"
        model: "Qwen/QwQ-32B"
        base_url: "https://router.huggingface.co/hf-inference/models/Qwen/QwQ-32B/v1"
      EOF
      
      # Sinalizar conclusão
      gp sync-done docker_ready

  - name: MetaGPT Runner
    command: |
      # Esperar Docker estar pronto
      gp sync-await docker_ready
      
      # Mensagem de boas-vindas
      echo -e "\n\033[32m✅ Ambiente Configurado!\033[0m"
      echo -e "Modelo: \033[36mQwen/QwQ-32B\033[0m"
      echo -e "API Key: ${HUGGINGFACE_QWQ32B:+*****}"
      echo -e "\n\033[1mComo usar:\033[0m"
      echo -e "1. Executar comando direto:"
      echo -e "   \033[36mmetagpt 'sua pergunta'\033[0m"
      echo -e "2. Acessar arquivos gerados:"
      echo -e "   \033[36mcd metagpt/workspace && ls\033[0m"
      
      # Criar alias para o comando
      echo -e "\nalias metagpt='docker run -it --rm --privileged \\
        -v $(pwd)/.metagpt/config2.yaml:/app/metagpt/config/config2.yaml \\
        -v $(pwd)/metagpt/workspace:/app/metagpt/workspace \\
        metagpt/metagpt:latest metagpt'" >> ~/.bashrc
      
      source ~/.bashrc

ports:
  - port: 3000
    onOpen: open-preview
    visibility: public