# .gitpod.yml
tasks:
  - name: Setup Python 3.11
    init: |
      pyenv install 3.11.9
      pyenv global 3.11.9
  - name: Install Dependencies
    init: |
      set -e  # Faz o script falhar imediatamente em caso de erro
      echo "Instalando MetaGPT e dependências..."
      python3 -m pip install --upgrade pip setuptools wheel
      pip install numpy==1.26.0  # Versão compatível com Python 3.11+
      pip install metagpt
      gp sync-done deps_installed
  - name: Welcome Message
    command: |
      gp sync-await deps_installed
      echo ""
      echo "✅ Tudo pronto! Use: metagpt 'sua pergunta'"
      echo "👉 Configure suas API keys em: https://gitpod.io/user/variables"
      echo ""
      
# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
ports:
  - name: Frontend
    description: Port 3000 for the frontend
    port: 3000
    onOpen: open-preview

# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart
